-- MySQL Script generated by MySQL Workbench
-- Fri Aug 23 15:55:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 2024kyledeleon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `2024kyledeleon` ;

-- -----------------------------------------------------
-- Schema 2024kyledeleon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `2024kyledeleon` DEFAULT CHARACTER SET utf8 ;
USE `2024kyledeleon` ;

-- -----------------------------------------------------
-- Table `2024kyledeleon`.`team_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2024kyledeleon`.`team_table` (
  `team_id` INT NOT NULL,
  `team_name` VARCHAR(45) NOT NULL,
  `venue_id` INT NOT NULL,
  PRIMARY KEY (`team_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2024kyledeleon`.`match_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2024kyledeleon`.`match_time` (
  `match_time` VARCHAR(45) NULL,
  `match_id` INT NOT NULL,
  `venue_id` INT NULL,
  `date` INT NULL,
  PRIMARY KEY (`match_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2024kyledeleon`.`quarter_point_ table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2024kyledeleon`.`quarter_point_table` (
  `match_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `set_1_points` INT NULL,
  `set_2_points` INT NULL,
  `set_3_points` INT NULL,
  `match time_match_id` INT NOT NULL,
  `team_table_team_id` INT NOT NULL,
  PRIMARY KEY (`match_id`, `team_id`),
  INDEX `fk_Points table_Match Time_idx` (`match time_match_id` ASC) ,
  INDEX `fk_Points table_Team_Table1_idx` (`team_table_team_id` ASC) ,
  CONSTRAINT `fk_Points table_Match Time`
    FOREIGN KEY (`match time_match_id`)
    REFERENCES `2024kyledeleon`.`match_time` (`match_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Points table_Team_Table1`
    FOREIGN KEY (`team_table_team_id`)
    REFERENCES `2024kyledeleon`.`team_table` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2024kyledeleon`.`semi_points_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2024kyledeleon`.`semi_points_table` (
  `match_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `set_1_points` INT NULL,
  `set_2_points` INT NULL,
  `set_3_points` INT NULL,
  `match_time_match_id` INT NOT NULL,
  `team_table_team_id` INT NOT NULL,
  PRIMARY KEY (`match_id`, `team_id`),
  INDEX `fk_Points table_Match Time_idx` (`match_time_match_id` ASC) ,
  INDEX `fk_Points table_Team_Table1_idx` (`team_table_team_id` ASC) ,
  CONSTRAINT `fk_Points table_Match Time0`
    FOREIGN KEY (`match_time_match_id`)
    REFERENCES `2024kyledeleon`.`match_time` (`match_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Points table_Team_Table10`
    FOREIGN KEY (`team_table_team_id`)
    REFERENCES `2024kyledeleon`.`team_table` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2024kyledeleon`.`final_points_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2024kyledeleon`.`final_points_table` (
  `match_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `set_1_points` INT NULL,
  `set_2_points` INT NULL,
  `set_3_points` INT NULL,
  `match_time_match_id` INT NOT NULL,
  `team_table_team_id` INT NOT NULL,
  PRIMARY KEY (`match_id`, `team_id`),
  INDEX `fk_Points table_Match Time_idx` (`match_time_match_id` ASC),
  INDEX `fk_Points table_Team_Table1_idx` (`team_table_team_id` ASC),
  CONSTRAINT `fk_Points table_Match Time1`
    FOREIGN KEY (`match_time_match_id`)
    REFERENCES `2024kyledeleon`.`match_time` (`match_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Points table_Team_Table11`
    FOREIGN KEY (`team_table_team_id`)
    REFERENCES `2024kyledeleon`.`team_table` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
